export default {
    SET_APPLES: 'SET_APPLES',
    SET_MOVIES: 'SET_MOVIES',
    SET_GENRES: 'SET_GENRES',
    ADD_ACTIVE_ACTION: 'ADD_ACTIVE_ACTION',
    REMOVE_ACTIVE_ACTION: 'REMOVE_ACTIVE_ACTION',
}